version: '2'
networks:
  default:
    driver: bridge

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./php:/data
    working_dir: /data
    depends_on:
      - kafka
      - schemaregistry
    networks:
      - default

  java:
    image: maven:3-jdk-8-alpine
    volumes:
      - ./java:/data
      - ./java/.m2:/root/.m2
    working_dir: /data
    depends_on:
      - kafka
      - schemaregistry
    networks:
      - default

  python:
    build:
      context: docker/python
    volumes:
      - ./python:/data
    working_dir: /data
    depends_on:
      - kafka
      - schemaregistry
    networks:
      - default

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - default

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - default

  schemaregistry:
    image: confluent/schema-registry
    depends_on:
      - zookeeper
      - kafka
    networks:
      - default
